apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7241eb8b8e18dac61e261ec40f537bb92ef3b538
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator
  labels:
    app.kubernetes.io/instance: squad4-meme-generator
    app.kubernetes.io/name: squad4-meme-generator
  name: squad4-meme-generator-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: squad4-meme-generator
    app.kubernetes.io/name: squad4-meme-generator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7241eb8b8e18dac61e261ec40f537bb92ef3b538
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator
  labels:
    app.kubernetes.io/instance: squad4-meme-generator
    app.kubernetes.io/name: squad4-meme-generator
  name: squad4-meme-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: squad4-meme-generator
      app.kubernetes.io/name: squad4-meme-generator
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 7241eb8b8e18dac61e261ec40f537bb92ef3b538
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator
      labels:
        app.kubernetes.io/instance: squad4-meme-generator
        app.kubernetes.io/name: squad4-meme-generator
    spec:
      containers:
      - image: quay.io/levandrejev/squad4-meme-generator:7241eb8b8e18dac61e261ec40f537bb92ef3b538
        name: squad4-meme-generator
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7241eb8b8e18dac61e261ec40f537bb92ef3b538
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator
  labels:
    app.kubernetes.io/instance: squad4-meme-generator
    app.kubernetes.io/name: squad4-meme-generator
  name: squad4-meme-generator-svc
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: squad4-meme-generator-svc
    weight: 100
  wildcardPolicy: None
